services:
  postgres:
    image: postgres:16-alpine
    container_name: ainuxt_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres} # Default: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres} # Default: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} # Default: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Default: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
